### ISSUE TITLE
ilxd SIGSEGV on faucet request

### ISSUE THREAD

**Issue by liber-tas** [project-illium/ilxd#5]
Running linux_386 version, got the below just after requesting a faucet distribution. Restarted, and everything seems to be fine again, including the coins requested being present in the wallet. 

2023-06-26T16:13:00-04:00  [INFO]  PeerID: 12D3KooWD3P1EwabbpjQnCwpdrXg1HtbBv1LzSuFpuDLyjAievG6
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip4/10.136.43.122/tcp/9002
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip4/10.136.43.122/udp/9002/quic
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip4/127.0.0.1/tcp/9002
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip4/127.0.0.1/udp/9002/quic
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip6/::1/tcp/9002
2023-06-26T16:13:00-04:00  [INFO]  Listening on /ip6/::1/udp/9002/quic
2023-06-26T16:13:00-04:00  [INFO]  gRPC server listening on /ip4/127.0.0.1/tcp/5001
2023-06-26T16:13:00-04:00  [INFO]  Wallet started. Syncing blocks to tip...
2023-06-26T16:13:01-04:00  [INFO]  Wallet sync complete.
2023-06-26T16:13:16-04:00  [INFO]  Blockchain synced to tip
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85248d3]

goroutine 433 [running]:
github.com/project-illium/ilxd/blockchain.(*ValidatorSet).WeightedRandomValidator(0xc55e2a0)
	/home/runner/work/ilxd/ilxd/blockchain/validatorset.go:568 +0x163
github.com/project-illium/ilxd/blockchain.(*Blockchain).WeightedRandomValidator(0xc55ea80)
	/home/runner/work/ilxd/ilxd/blockchain/chain.go:378 +0x8a
github.com/project-illium/ilxd/consensus.(*BackoffChooser).WeightedRandomValidator(0xc830030)
	/home/runner/work/ilxd/ilxd/consensus/chooser.go:38 +0x2b
github.com/project-illium/ilxd/consensus.(*ConsensusEngine).pollLoop(0xc83e000)
	/home/runner/work/ilxd/ilxd/consensus/engine.go:463 +0x67
github.com/project-illium/ilxd/consensus.(*ConsensusEngine).handler(0xc83e000)
	/home/runner/work/ilxd/ilxd/consensus/engine.go:181 +0x205
created by github.com/project-illium/ilxd/consensus.NewConsensusEngine
	/home/runner/work/ilxd/ilxd/consensus/engine.go:154 +0x5b2

**Comment by liber-tas** [comment]
Looks like the same error occurs when spending: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85248d3]

goroutine 565 [running]:
github.com/project-illium/ilxd/blockchain.(*ValidatorSet).WeightedRandomValidator(0xb4d8070)
	/home/runner/work/ilxd/ilxd/blockchain/validatorset.go:568 +0x163
github.com/project-illium/ilxd/blockchain.(*Blockchain).WeightedRandomValidator(0xb4d80e0)
	/home/runner/work/ilxd/ilxd/blockchain/chain.go:378 +0x8a
github.com/project-illium/ilxd/consensus.(*BackoffChooser).WeightedRandomValidator(0xb738af0)
	/home/runner/work/ilxd/ilxd/consensus/chooser.go:38 +0x2b
github.com/project-illium/ilxd/consensus.(*ConsensusEngine).pollLoop(0xb55aa80)
	/home/runner/work/ilxd/ilxd/consensus/engine.go:463 +0x67
github.com/project-illium/ilxd/consensus.(*ConsensusEngine).handler(0xb55aa80)
	/home/runner/work/ilxd/ilxd/consensus/engine.go:181 +0x205
created by github.com/project-illium/ilxd/consensus.NewConsensusEngine
	/home/runner/work/ilxd/ilxd/consensus/engine.go:154 +0x5b2

**Comment by cpacia** [comment]
Thank you for testing this out. 

The bug is interesting because I'm skipping the error check on the `weightedrand.NewChooser` constructor. Which obviously would panic if the chooser is accessed after there was an error in the constructor. 

But there can only be an error in the constructor if:
1. There are zero validators. 
2. The total stake overflows an int64.

**Comment by cpacia** [comment]
Oh you said you're on  linux_386. That cause an overflow if it's over an int32, which it might be.

**Comment by cpacia** [comment]
I think the only way to fix this is to fork the WeightedRand library.

**Comment by cpacia** [comment]
If you want to try pulling from master it should be fixed now.
