### ISSUE TITLE
Refactor sample config

### ISSUE THREAD

**Issue by cpacia** [project-illium/ilxd#85]
The sample config uses bindata, but go now has an embed package that can be used instead. So update the sample config to use embed.

While were at it, run through the sample config an make sure all the config options are represented in it and the values are accurate.

**Comment by iskiy** [comment]
I'm ready to work on it, assign it to me.

**Comment by cpacia** [comment]
Sure if you want to go ahead.

Here's an example of using embed: https://github.com/project-illium/ilxd/blob/master/zk/scripts.go#L17

And here's the config options: https://github.com/project-illium/ilxd/blob/master/repo/config.go#L46
